config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  get '/history', to: 'home#history'
  post '/create_log', to: "home#create_log"
  get '/log', to: 'home#log'
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
  validates :date_payed, :result, :opponent_id, :user_id, :opponent_score, :my_score, presence: true

  validate :check_scores


  def check_scores
    score = (opponent_score - my_score)
    puts score = score.abs

    errors.add(:opponent_score, "The score can't be equal") if opponent_score == my_score
    errors.add(:result, "The win score has to be grater than 2") unless score > 2
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :trackable, :validatable

  has_many :games, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.order(ranking: :desc)
    
  end

  def history
    @games = Game.where(user_id: current_user.id).order(date_payed: :desc)
  end

  def log
    @game_log = Game.new
  end


  def create_log
    game = Game.new(game_params)
    game.user_id = current_user.id

    # Calculates the result of the game
    if game.my_score.to_i > game.opponent_score.to_i
      game.result = 'win'
    else
      game.result = 'lose'
    end

    
    if game.save
      # if game save, modify ranking of players
      opponent = User.find(game.opponent_id.to_i)
      opponent_ranking = opponent.ranking.to_i 
      my_ranking = game.user.ranking.to_i
      game.user.ranking = 1/(1+((10)**((opponent_ranking - my_ranking)/400)))
      opponent.ranking = 1/(1+((10)**((my_ranking - opponent_ranking)/400)))
      game.user.save
      opponent.save

      redirect_to :history
    else
      render :log
      puts game.errors.messages
    end
  end
  private
    def game_params
      params.require(:game).permit(:date_payed, :opponent_id, :my_score, :opponent_score)
    end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/history.html.erb
<h1 class='page-header'>History</h1>

<table class="table">
  <thead>
    <tr>
      <td>Date</td>
      <td>Opponent</td>
      <td>Score</td>
      <td>Result</td>
    </tr>
  </thead>
  <tbody>
      <% @games.each do |game| %>
        <tr>
        <td><%= game.date_payed.strftime("%b %d") %></td>
        <td><%= game.opponent_id %></td>
        <td><%= "#{game.my_score} - #{game.opponent_score } "%></td>
        <td><%= game.result %></td>
       </tr>
      <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<h1 class='page-header'>Leaderboard</h1>

<table class="table">
  <thead>
    <tr>
      <td>Rank</td>
      <td>Name</td>
      <td>Score ranking</td>
      <td>Games played</td>
    </tr>
  </thead>
  <tbody>
      <% @users.each_with_index do |user, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= user.email %></td>
          <td><%= user.ranking %></td>
          <td><%= user.games.count %></td>
       </tr>
      <% end %>
  </tbody>
</table>

app/views/home/log.html.erb
<h1 class='page-header'>Log Game</h1>

<%= form_for @game_log = Game.new, url: create_log_path do |f| %>
  <p>
    <%= f.label(:date_payed, "Date Played: ") %>    
    <%= f.date_field(:date_payed, required: true) %>    
  </p>
  <p>
    <%= f.label(:opponent_id, "Opponent: ") %>    
    <%= f.collection_select(:opponent_id, User.where.not(email: current_user.email), :id, :email) %>    
  </p>
  <p>
    <%= f.label(:my_score, "Your Score: ") %>    
    <%= f.number_field(:my_score, required: true) %>    
  </p>
  <p>
    <%= f.label(:opponent_score, "Opponent Score: ") %>    
    <%= f.number_field(:opponent_score, required: true) %>    
  </p>
    <%= f.submit("Save") %> | <%= link_to "Cancel", root_path %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Pingpong</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= link_to 'Log Game', '/log', class: 'btn btn-success navbar-btn' %>
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Leadboard', root_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><a href="/history">History</a></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pingpong Leaderboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css", integrity: "sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js", integrity: "sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>